### ISSUE TITLE
Suggestion: Text Decoration Support (Bold, etc.)

### ISSUE THREAD

**Issue by slooshied** [Iridium-Development/IridiumColorAPI#2]
Hello! I am very fond of your API as it is very useful! I was wondering, however, if there is a current way to make decorated text with the gradient & solid methods you have provided. Currently, from what I have tried, the photo is the result. Thanks for your help & work on this API.

![sample12313213](https://user-images.githubusercontent.com/70556905/106371725-52dfaa00-632d-11eb-9e6d-7e52162b95a2.PNG)

**Comment by PeachesMLG** [comment]
Fixed: https://github.com/Iridium-Development/IridiumColorAPI/commit/82819f14a836916c26b697c2ed4c9d2e5262090f

**Comment by slooshied** [comment]
This is wonderful news! To be correct, would the decorative code would go inbetween the html? For example: `<GRADIENT:#FFFFFF>&lThis is a bold message</GRADIENT:#FFFFFF>`?
