### ISSUE TITLE
Multiple Gradients

### ISSUE THREAD

**Issue by CroaBeast** [Iridium-Development/IridiumColorAPI#20]
Good day,
I want to know if it's possible to add multiple gradient formats to a single text.
Example: `<GRADIENT:FFFFFF>my awesome<GRADIENT:FFF000>message</GRADIENT:000000>`

**Comment by TonyMontero** [comment]
A better formatting:
<GRADIENT:D52D00:FF9A56:FFFFFF:D362A4:A30262>LOOK AT ME MOM!</GRADIENT>

**Comment by KaspianDev** [comment]
+1

**Comment by CroaBeast** [comment]
I fork this API and make it to support multiple gradients, you can see it [here](https://github.com/CroaBeast/BeansLib/blob/fbd8eaed3b0903b3d90ca374567a1987e7505e4d/src/main/java/me/croabeast/iridiumapi/IridiumAPI.java#L111).
