### ISSUE TITLE
Gridient doesn't work

### ISSUE THREAD

**Issue by toto7735** [Iridium-Development/IridiumColorAPI#21]
<GRADIENT:...>...</GRADIENT:...> Doesn't work

Code:
FancyColor.process("<GRADIENT:#33CD33>ஂGuide</GRADIENT:#84E184> §a")

<RAINBOW> is works well

**Comment by PeachesMLG** [comment]
well FancyColor isnt the right class name, are you even using our API?
You also completly messed up the formatting and forgot to use the tags <> on the first gradient
