### ISSUE TITLE
Gradient sometimes incorrectly colors strings

### ISSUE THREAD

**Issue by GavvyDizzle** [Iridium-Development/IridiumColorAPI#28]
Sometimes when using a gradient on a string, a single character will become white instead of its usual color. This always happens when converting some length string with some gradient.

Examples:
`<GRADIENT:0FE7CD>Mine Tokens</GRADIENT:5D8AFF>`
![image](https://user-images.githubusercontent.com/57154434/229667932-f2a90c14-28c1-4b41-a138-560a167c7a59.png)

`<GRADIENT:64FF10>Vote Tokens</GRADIENT:379B32>`
![image](https://user-images.githubusercontent.com/57154434/229667968-f74a30aa-b0ba-446d-80ac-c2f29be9d8e8.png)

**Comment by lerndmina** [comment]
Hey, just commenting to say I have the same issue even with one of the example strings in the [Readme](https://github.com/Iridium-Development/IridiumColorAPI/blob/master/README.md) If I change the length then some of the characters become white. This happens both in chat and on the scoreboard.

![image](https://user-images.githubusercontent.com/10632157/232315061-e3d17f8f-55a6-417f-b72d-2c2e39bb92ea.png)

I'm on Paper 1.19.4 btw

**Comment by GavvyDizzle** [comment]
After more testing, I discovered this was an issue with my resource pack. Turning it off caused the white characters to disappear.

I can confirm the following (for gradients):
- This API colors the characters correctly
- The server interprets the color correctly

For anyone who stumbles across this, I am using VanillaTweaks as my resource pack. It is caused by Dark UI.
edit: This is no longer present in 1.21+ versions of Dark UI
