### ISSUE TITLE
any support for reverting colored text to raw for storing in a configuration file?

### ISSUE THREAD

**Issue by portlek** [Iridium-Development/IridiumColorAPI#6]

**Comment by PeachesMLG** [comment]
Just store it as
```
"<GRADIENT:09C6F9>&lIridiumSkyblock</GRADIENT:045DE9> &8»"
```
In the config?

**Comment by portlek** [comment]
i want to store item stack's name and lore too, its not just a string. anyway i made my own library to colorize and also decolorize so the issue no important for me now.
